name: Test
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Upload The test Report to Artfacts
        uses: actions/upload-artifact@v2
        with:
          name: test-report-artifact
          path: test-report.html
